version: "{branch} {build}"

init:  
  - git config --global core.autocrlf true

environment:
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -mx0 -mmt=0 -snl -snh
  MAVEN_OPTS: "-Dmaven.repo.local=C:/Users/appveyor/.m2"
  JAVA_HOME: "C:/Program Files/Java/jdk1.8.0"

cache:
  - C:\Users\appveyor\.m2 -> pom.xml

install:
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - java -version

build_script:
  - mvn clean compile -DskipTests -P checker-framework
 
test_script:
  - mvn test
